url:
baseurl:
title:
gtm_id: GTM-KVZR5ZR
language_data: data.lang.%%
language_includes_dir: _i18n
defaults:
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-last-modified-at
  - jekyll-language-plugin
sass:
  sass_dir: _sass
  style: compressed