url:
baseurl:
title:
gtm_id: KVZR5ZR
language_data: data.lang.%%
language_includes_dir: _i18n
defaults:
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-last-modified-at
  - jekyll-language-plugin
sass:
  sass_dir: _sass
  style: compressed
defaults:
  -	
    scope:	
      type: "posts" # previously `post` in Jekyll 2.2.	
    values:	
      layout: "post"	
      permalink: /:day/:month/:year/:title/	
      language: fr	
  -	
    scope:	
      type: "pages" # previously `post` in Jekyll 2.2.	
    values:	
      layout: "default"	
      language: fr